version: '3'

services:
  api:
    container_name: api-container
    image: node:12
    working_dir: /home/node/app
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ./dist/:/home/node/app/dist/
      - ./package.json:/home/node/app/package.json
    ports:
      - '5050:5050'
      - '9222:9222'