version: '3'

services:
  mongo:
    image: mongo:4.4.1
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - '27017:27017'
  api:
    build: .
    env_file: ./.env
    restart: always
    environment:
      - MONGO_URL=$MONGO_URL
    volumes:
      - .:/home/node/app
    ports:
      - $PORT:$PORT
      - '9222:9222'
    depends_on:
      - mongo
    links:
      - mongo
volumes:
  mongodb: